require "prawn"
require "prawn/table"

class OnboardingPdfGenerator
  BRAND_DARK = "15385E"
  GRAY       = "6B7280"
  BLACK      = "111827"
  GREEN      = "059669"
  WHITE      = "FFFFFF"
  ROW_ALT    = "F9FAFB"

  def initialize(onboarding)
    @o    = onboarding
    @user = onboarding.user
  end

  def generate
    pdf = Prawn::Document.new(
      page_size: "LETTER",
      margin:    [36, 48, 48, 48]
    )

    draw_header(pdf)
    section(pdf, "General Information")
    table_rows(pdf, [
      ["Request Date",      fmt_date(@o.request_date)],
      ["Employee Name",     @user.full_name],
      ["Employee Email",    @user.email],
      ["Title / Position",  @user.position.presence || "—"],
      ["Department",        @user.department&.name.presence || "—"],
      ["Start Date",        fmt_date(@o.start_date)]
    ])

    section(pdf, "Computer Assignment")
    rows = [["New Computer", yn(@o.new_computer?)]]
    unless @o.new_computer?
      rows << ["PC Name / Previous Owner", @o.pc_name_or_previous_owner.presence || "—"]
      rows << ["Asset Tag",               @o.pc_asset_tag.presence || "—"]
    end
    table_rows(pdf, rows)

    section(pdf, "Remote Access")
    rows = [["Remote Access Needed", yn(@o.remote_access_needed?)]]
    if @o.remote_access_needed?
      rows << ["New Remote User", yn(@o.new_remote_user?)]
      unless @o.new_remote_user?
        rows << ["Remote User",       @o.previous_remote_user.presence || "—"]
        rows << ["Remote Department", @o.remote_department.presence || "—"]
      end
    end
    table_rows(pdf, rows)

    section(pdf, "Local PC Applications")
    apps = Array(@o.applications)
    apps << "Other: #{@o.applications_other}" if @o.applications_other.present?
    pdf.text(apps.any? ? apps.join("   |   ") : "None selected.",
             size: 10, color: apps.any? ? BLACK : GRAY, leading: 4)
    pdf.move_down 8

    section(pdf, "Telephony")
    table_rows(pdf, [
      ["Existing Phone",   yn(@o.existing_phone?)],
      ["Extension Number", @o.extension&.number&.to_s || "—"]
    ])

    if @o.notes.present?
      section(pdf, "Notes / Additional Comments")
      pdf.text @o.notes, size: 10, color: BLACK, leading: 4
    end

    draw_footer(pdf)
    pdf.render
  end

  private

  def draw_header(pdf)
    pdf.fill_color BRAND_DARK
    pdf.fill_rectangle [pdf.bounds.left - 48, pdf.cursor + 36], pdf.bounds.width + 96, 68
    pdf.fill_color WHITE
    pdf.text_box "Onboarding Request",
      at: [pdf.bounds.left, pdf.cursor + 18], width: pdf.bounds.width,
      size: 20, style: :bold, align: :center
    pdf.text_box "Interworld Freight  -  IT Department",
      at: [pdf.bounds.left, pdf.cursor - 6], width: pdf.bounds.width,
      size: 11, align: :center
    pdf.fill_color BLACK
    pdf.move_down 50
  end

  def section(pdf, title)
    pdf.move_down 12
    pdf.fill_color BRAND_DARK
    pdf.fill_rectangle [pdf.bounds.left, pdf.cursor + 2], pdf.bounds.width, 17
    pdf.fill_color WHITE
    pdf.text_box title,
      at: [pdf.bounds.left + 6, pdf.cursor],
      width: pdf.bounds.width - 12, size: 10, style: :bold
    pdf.fill_color BLACK
    pdf.move_down 18
  end

  def table_rows(pdf, rows)
    return if rows.empty?
    data = rows.map.with_index do |(label, value), i|
      bg = i.even? ? WHITE : ROW_ALT
      [
        { content: label, font_style: :bold, text_color: GRAY,  background_color: bg },
        { content: value.to_s, text_color: BLACK, background_color: bg }
      ]
    end
    pdf.table(data,
      width:         pdf.bounds.width,
      cell_style:    { size: 10, padding: [5, 8], border_color: "E5E7EB", border_width: 0.5 },
      column_widths: [pdf.bounds.width * 0.42, pdf.bounds.width * 0.58]
    )
    pdf.move_down 4
  end

  def draw_footer(pdf)
    pdf.repeat(:all) do
      pdf.fill_color GRAY
      pdf.draw_text "Generated by IWF Hub  -  #{Date.today.strftime('%B %d, %Y')}",
        at: [pdf.bounds.left, -24], size: 8
      pdf.fill_color BLACK
    end
  end

  def yn(val) = val ? "Yes" : "No"
  def fmt_date(date) = date&.strftime("%B %d, %Y") || "—"
end